default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gnt_pop_development

test:
  <<: *default
  database: gnt_pop_test

production:
  primary:
    <<: *default
    database: gnt_pop_production
  queue:
    <<: *default
    database: gnt_pop_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: gnt_pop_production_cable
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    database: gnt_pop_production_cache
    migrations_paths: db/cache_migrate
